name: CI golang

on:
  workflow_call:
    inputs:
      ignore_bp3:
        required: false
        type: string
      commit_name:
        required: false
        type: string

jobs: 

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel running workflows
      env: 
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        repo: ${{ GITHUB.REPOSITORY }}
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/cancelworkflow.sh | bash 

    - name: Check PR true
      if: ${{ inputs.ignore_bp3 == 'true' }}
      run: |
        echo "ignore_bp3 = true"
        echo "update voedger dependency '${{ inputs.commit_name }}'"

    - name: Check PR false
      if: ${{ inputs.ignore_bp3 == 'false' }}
      run: |
        echo "ignore_bp3 = true"
        echo "update voedger dependency '${{ inputs.commit_name }}'"

