name: Merge PR

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vulnerability management
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
