name: Daily test suite

on: [push]

jobs:
  call-workflow-ci:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      ignore_bp3: 'true'
      short_test: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
