name: Check PR and Merge PR

on: [pull_request_target]

jobs:
  call-workflow-check_commits:
    uses: ivvist/ci-action/.github/workflows/ci_reuse_go_pr.yml@master
    with: 
      ignore_copyright: 'true'
      ignore_bp3: 'true'
      short_test: 'true'
      running_workflow: 'Check PR and Merge PR'	
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  auto-merge-pr:
    needs: call-workflow-check_commits
    uses: voedger/voedger/.github/workflows/merge.yml@main
    secrets:
      personaltoken: ${{ secrets.REPOREADING_TOKEN }}


