name: Test success

on: [push]

jobs:
  call-workflow-show_time:
    uses: ivvorg/public-test-repo/.github/workflows/show_time.yml@main
    outputs:
      status: ${{ job.status }}
  call-workflow-ci:
    needs: call-workflow-show_time
    if: always()
    uses: ivvorg/public-test-repo/.github/workflows/show_time.yml@main
    
