name: Test success

on: [push]

jobs:
  call-workflow-show_time:
    uses: ./.github/workflows/show_time.yml
  notify_failure:
    needs: call-workflow-show_time
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    outputs:
      failure_url: ${{ steps.set_output.outputs.failure_url }}  # Declaring output at the job level
    steps:
      - name: Set Failure URL Output
        id: set_output
        run: 
          echo "failure_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT
  call-workflow-ci:
    needs: notify_failure
    if: ${{ !failure() }}
    uses: ./.github/workflows/create_issue.yml
    with: 
      repo: 'IVVORG/public-test-repo' 
      assignee: 'upload-robot'
      name: 'issue for test'
      body: ${{ needs.notify_failure.outputs.failure_url }}
    secrets:
      personaltoken: ${{ secrets.PERSONAL_TOKEN }}

    


    
