name: Test success

on: [push]

jobs:
  call-workflow-show_time:
    uses: ./.github/workflows/show_time.yml
  call-workflow-ci:
    needs: call-workflow-show_time
    if: ${{ needs.call-workflow-show_time.result == 'success' }}
    uses: ./.github/workflows/create_issue.yml
    with: 
      repo: 'IVVORG/public-test-repo' 
      assignee: 'upload-robot'
      name: 'issue for test'
      body: 'Test did not pass'

    


    
