name: Test success

on: [push]

jobs:
  call-workflow-show_time:
    uses: ivvorg/public-test-repo/.github/workflows/show_time.yml@main
  call-workflow-ci:
    uses: ivvorg/public-test-repo/.github/workflows/show_time.yml@main
