name: Test success

on: [push]

jobs:
  call-workflow-show_time:
    uses: ./.github/workflows/show_time.yml@main
    outputs:
      job1_status: ${{ job.status }}
  call-workflow-ci:
    needs: call-workflow-show_time
    if: ${{ needs.call-workflow-show_time.outputs.job1_status != 'success' }}
    uses: ivvorg/public-test-repo/.github/workflows/show_time.yml@main

    
