name: Check PR and Merge PR

on: [pull_request]

jobs:
  call-workflow-check:
    uses: ivvorg/public-test-repo/.github/workflows/check.yml@main
    with: 
      ignore_bp3: 'true'
      commit_name: "${{ github.event.head_commit.message }} ${{ github.event.head_commit.id }}"      
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go_pr.yml@master
    with: 
      ignore_copyright: 'true'
      ignore_bp3: 'true'
      short_test: 'true'
      running_workflow: 'Check PR and Merge PR'	
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
  call-workflow-vulncheck:
    needs: call-workflow-check
    uses: ivvorg/public-test-repo/.github/workflows/ci-extrachecks.yml@main


