name: Check PR and Merge PR

on: [push]

jobs:
  call-workflow-check:
    uses: ivvorg/public-test-repo/.github/workflows/check.yml@main
    with: 
      ignore_bp3: 'true'
  call-workflow-vulncheck:
    needs: call-workflow-ci
    uses: ivvorg/public-test-repo/.github/workflows/ci-extrachecks.yml@main


