name: Check PR and Merge PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  call-workflow-check:
    uses: ivvorg/pub-demo/.github/workflows/check.yml@main
  call-workflow-merge:
    needs: call-workflow-check
    uses: ivvorg/pub-demo/.github/workflows/mymerge.yml@main
    secrets:
      personaltoken: ${{ secrets.PERSONAL_TOKEN }}
