name: CI golang

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-check:
    uses: IVVORG/public-test-repo/.github/workflows/check.yml@main
  call-workflow-merge:
    needs: call-workflow-check
    uses: IVVORG/public-test-repo/.github/workflows/merge.yml@main
