name: Check PR and Merge PR

on:
  push:
    paths:
      - 'folder-2/**'
  pull_request:
    paths:
      - 'folder-2/**'

jobs:
  call-workflow-check:
    uses: ivvorg/public-test-repo/.github/workflows/check2.yml@main
