name: Cherry Pick Commits on Issue Creation

on: 
  issues:
    types: [opened, reopened]

jobs: 
  add-issue-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Unlink issue from milestone
      env: 
        GH_TOKEN: ${{ secrets.REPOREADING_TOKEN }} 
        org: 'IVVORG'
        repo: 'public-test-repo'
        issue: '${{ github.event.issue.id }}'
        body: 'This is a comment with a link to the running workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}';
      run: |
        chmod +x ./.github/workflows/add-issue-commit.sh
        bash ./.github/workflows/add-issue-commit.sh 

#  cherry-pick:
#    uses: ./.github/workflows/wf-sp.yml
#    with: 
#      org: 'IVVORG'
#      repo: 'public-test-repo'
#      team: 'DevOps_cp'
#      user: '${{ github.event.issue.user.login }}'
#      issue-title: '${{ github.event.issue.title }}'
#      issue-body: '${{ github.event.issue.body }}'
#    secrets:
#      git_token: ${{ secrets.REPOREADING_TOKEN }}

