name: Cherry Pick Commits on Issue Creation

on:
  issues:
    types: [opened]

jobs:

  cherry-pick:
    uses: ./.github/workflows/wf-sp.yml
    with: 
      org: 'IVVORG'
      repo: 'public-test-repo'
      team: 'DevOps_cp'
      user: '${{ github.event.issue.user.login }}'
      issue-title: '${{ github.event.issue.title }}'
      issue-body: '${{ github.event.issue.body }}'
    secrets:
      github_token: ${{ secrets.REPOREADING_TOKEN }}

