name: Cherry Pick Commits on Issue Creation

on:  
  issues:
    types: [opened]

jobs: 
  add-issue-comment:
    if: |
      github.event.issue.title != '' &&
      (
        startsWith(github.event.issue.title, 'cprc') ||
        startsWith(github.event.issue.title, 'cprelease')
      )    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create issue comment
      env: 
        GH_TOKEN: ${{ secrets.REPOREADING_TOKEN }} 
        org: 'IVVORG'
        repo: 'public-test-repo'
        issue: '${{ github.event.issue.number }}'
        body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        bash ./.github/workflows/add-issue-commit.sh

  cherry-pick:
    needs: add-issue-comment
    uses: ./.github/workflows/wf-sp.yml
    with: 
      org: 'IVVORG'
      repo: 'public-test-repo'
      team: 'DevOps_cp'
      user: '${{ github.event.issue.user.login }}'
      issue-title: '${{ github.event.issue.title }}'
      issue-body: '${{ github.event.issue.body }}'
    secrets:
      git_token: ${{ secrets.REPOREADING_TOKEN }}

  close-issue:
    needs: cherry-pick
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Close issue 
      env: 
        GH_TOKEN: ${{ secrets.REPOREADING_TOKEN }} 
        org: 'IVVORG'
        repo: 'public-test-repo'
        issue: '${{ github.event.issue.number }}'
      run: |
        bash ./.github/workflows/close-issue.sh

