name: Cherry Pick Commits on Issue Creation

on:
  issues:
    types: [push]

jobs:

  add-issue-comment:
    # Use GitHub Script to add a comment
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Add comment to issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // The GitHub context object contains useful information about the current workflow
            const context = github.context;

            // Specify the issue number you want to comment on
            const issue_number = 414;

            // Construct the workflow run URL
            const workflow_run_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            // Create the comment content
            const body = `This is a comment with a link to the running workflow: [Workflow Run #${context.runNumber}](${workflow_run_url})`;

            // Add a comment to the specified issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });

#  cherry-pick:
#    uses: ./.github/workflows/wf-sp.yml
#    with: 
#      org: 'IVVORG'
#      repo: 'public-test-repo'
#      team: 'DevOps_cp'
#      user: '${{ github.event.issue.user.login }}'
#      issue-title: '${{ github.event.issue.title }}'
#      issue-body: '${{ github.event.issue.body }}'
#    secrets:
#      git_token: ${{ secrets.REPOREADING_TOKEN }}

