name: Cherry Pick Commits on Issue Creation

on: [push]
#  issues:
#    types: [opened]

jobs:

  add-issue-comment:
    # Use GitHub Script to add a comment
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to cherry pick issue
        run: |
          chmod +x ./.github/workflows/add-issue-commit.sh
          bash ./.github/workflows/add-issue-commit.sh 
        with: 
          github_token: ${{ secrets.REPOREADING_TOKEN }}
          GH_TOKEN: ${{ secrets.REPOREADING_TOKEN }} 
          org: 'IVVORG'
          repo: 'public-test-repo'
          issue: '${{ github.event.issue.id }}'
          body: 'This is a comment with a link to the running workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}';

#  cherry-pick:
#    uses: ./.github/workflows/wf-sp.yml
#    with: 
#      org: 'IVVORG'
#      repo: 'public-test-repo'
#      team: 'DevOps_cp'
#      user: '${{ github.event.issue.user.login }}'
#      issue-title: '${{ github.event.issue.title }}'
#      issue-body: '${{ github.event.issue.body }}'
#    secrets:
#      git_token: ${{ secrets.REPOREADING_TOKEN }}

