name: Release every 2 weeks at 5 at the morning

on:
  schedule:
    - cron: '0 4 1-7 * 2'
    - cron: '0 4 15-21 * 2'

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Release note
      run: |
         echo "It's released"


