name: Link issue to Milestone

on:
  issues:
    types: [closed]

jobs: 
  link:
    runs-on: ubuntu-latest

    steps:
    - name: Link tissue to milestone
      env: 
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        repo: ${{ GITHUB.REPOSITORY }}
        issue: ${{ github.event.issue.number }}
      run: curl -s https://raw.githubusercontent.com/ivvist/ci-action/master/scripts/linkmilestone5.sh | bash 

