name: Link issue to Milestone

on:
  issues:
    types: [closed]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: link
      env: 
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: curl -s https://raw.githubusercontent.com/ivvist/ci-action/master/scripts/linkmilestone.sh | bash 
