name: Link issue to Milestone

on:
  issues:
    types: [closed]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: link
      env: 
        GH_TOKEN: ${{ secrets.personaltoken }}
      run: ivvorg/public-test-repo/linkmilestone.sh | bash 
