name: Link issue to Milestone

on:
  issues:
    types: [closed]
    secrets:
      personaltoken:
        required: true

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: link
      env: 
        GH_TOKEN: ${{ secrets.personaltoken }}
        token: ${{ secrets.personaltoken }}
      run: curl -s https://raw.githubusercontent.com/ivvist/ci-action/master/scripts/linkmilestone.sh | bash 
