name: Merge with juliangruber

on:
  workflow_call

jobs:
  merge-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Approve Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 1
        method: squash # merge rebase
        repo: ivvorg/pub-demo # optional