name: CD golang

on:
  workflow_call

jobs:
  merge-pull-request:
    runs-on: ubuntu-latest
  steps:
    - name: Approve Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 81
        method: squash # merge rebase
        repo: ivvorg/public-test-repo # optional