name: Merge PR1

on:
  workflow_call:
    secrets:
      personaltoken:
        required: true

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Merge PR
      env: 
        GH_TOKEN: ${{ secrets.personaltoken }}
        pr_number: ${{ github.event.number }}
        repo: ${{ GITHUB.REPOSITORY }}
      run: |
        echo "secrets.personaltoken: ${{ secrets.personaltoken }}"
        prname="https://github.com/$GITHUB_REPOSITORY/pull/${{ github.event.number }}"
        echo "repo: https://github.com/${{ env.repo }}/pull/${{ env.pr_number }}"
        gh pr merge https://github.com/${{ env.repo }}/pull/${{ env.pr_number }} --squash

