name: make reelase candidate

on:  
  issues:
    types: [opened]

jobs: 
  cherry-pick:
    if: |
      github.event.issue.title != '' &&
      (
        startsWith(github.event.issue.title, 'rc') 
      )    
    uses: ./.github/workflows/rc1.yml
    with: 
      org: 'IVVORG'
      repo: 'public-test-repo'
      team: 'DevOps_cp'
      user: '${{ github.event.issue.user.login }}'
    secrets:
      git_token: ${{ secrets.REPOREADING_TOKEN }}

