name: CI golang

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR
      run: |
        echo "good one"

    - name: Merge PR
      if: github.event_name == 'pull_request'
      env: 
        GH_TOKEN: ${{ github.token }}
        pr_number: ${{ github.event.number }}
        pr_org: ${{ GITHUB_REPOSITORY }}
        pr_repo: "repo"
      run: curl -s https://raw.githubusercontent.com/ivvist/ci-action/master/scripts/mergePR.sh | bash 


