name: CI golang

on: [pull_request]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Merge Pull Request
      uses: juliangruber/approve-pull-request-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 1
         
