name: CI golang

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR
      run: |
        echo "good one"

    - name: Merge PR
      env: 
        GH_TOKEN: ${{ github.token }}
        pr_number: ${{ github.event.number }}
      run: |
        echo "https://github.com/$GITHUB_REPOSITORY/pull/${{ github.event.number }}"
        gh pr merge https://github.com/$GITHUB_REPOSITORY/pull/${{ github.event.number }} --squash --admin



