name: My Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "export MY_TOKEN=${{ secrets.PERSONAL_TOKEN }}" >> $GITHUB_ENV
      - name: Use environment variable
        run: echo "My token is $MY_TOKEN"